import type { Metadata } from 'next';
import '../../styles/globals.css';
import Header from '../../layouts/Header';
import React from 'react';

export const metadata: Metadata = {
    title: 'toss뿌로젝트',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
