import type { Metadata } from 'next';
import React from 'react';
import '../../../styles/globals.css';
import Mypage from '../../../layouts/Mypage';

export const metadata: Metadata = {
    title: 'toss뿌로젝트',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Mypage>{children}</Mypage>
            </body>
        </html>
    );
}
